# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('predators', models.CharField(max_length=100)),
                ('num_restaurants', models.IntegerField()),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
